/* ==========================================================================
   Shared mock data used across admin pages.
   In production, this data comes from the API.
   ========================================================================== */

export const ORDERS = [
  { id: '1042', num: 1042, date: 'Apr 5, 2026 2:23 pm', customer: 'Sarah Chen', email: 'sarah.chen@gmail.com', items: [{ title: 'Classic Cotton T-Shirt', variant: 'M / White', qty: 2, price: 2499 }, { title: 'Wool Beanie', variant: 'One Size / Navy', qty: 1, price: 1999 }], subtotal: 6997, shipping: 599, tax: 560, discount: 0, total: 8156, payment: 'paid', fulfillment: 'unfulfilled', address: { name: 'Sarah Chen', line1: '742 Evergreen Terrace', city: 'Portland', state: 'OR', zip: '97201', country: 'US' }, timeline: [{ time: 'Apr 5, 2:23 pm', event: 'Order placed', detail: 'Customer placed order from Online Store' }, { time: 'Apr 5, 2:24 pm', event: 'Payment captured', detail: '$81.56 via Stripe (Visa ending 4242)' }] },
  { id: '1041', num: 1041, date: 'Apr 5, 12:10 pm', customer: 'James Wilson', email: 'james.wilson@outlook.com', items: [{ title: 'Slim Fit Jeans', variant: '32 / Indigo', qty: 1, price: 5999 }], subtotal: 5999, shipping: 599, tax: 480, discount: 0, total: 7078, payment: 'paid', fulfillment: 'fulfilled', address: { name: 'James Wilson', line1: '15 Oak Lane', city: 'Austin', state: 'TX', zip: '73301', country: 'US' }, timeline: [{ time: 'Apr 5, 12:10 pm', event: 'Order placed', detail: '' }, { time: 'Apr 5, 12:11 pm', event: 'Payment captured', detail: '$70.78 via Stripe' }, { time: 'Apr 5, 3:00 pm', event: 'Fulfilled', detail: '1 item shipped via USPS' }] },
  { id: '1040', num: 1040, date: 'Apr 5, 9:45 am', customer: 'Amira Patel', email: 'amira.patel@yahoo.com', items: [{ title: 'Leather Belt', variant: 'M / Brown', qty: 1, price: 3499 }, { title: 'Canvas Sneakers', variant: '9 / White', qty: 1, price: 4999 }, { title: 'Hooded Sweatshirt', variant: 'L / Black', qty: 1, price: 6999 }], subtotal: 15497, shipping: 0, tax: 1240, discount: 1550, total: 15187, payment: 'pending', fulfillment: 'unfulfilled', address: { name: 'Amira Patel', line1: '88 Maple Ave', city: 'Brooklyn', state: 'NY', zip: '11201', country: 'US' }, timeline: [{ time: 'Apr 5, 9:45 am', event: 'Order placed', detail: '' }, { time: 'Apr 5, 9:45 am', event: 'Payment pending', detail: 'Awaiting payment confirmation' }] },
  { id: '1039', num: 1039, date: 'Apr 4, 10:30 pm', customer: 'Lucas Berg', email: 'lucas.berg@proton.me', items: [{ title: 'Running Shoes', variant: '10 / Black', qty: 1, price: 8999 }], subtotal: 8999, shipping: 599, tax: 720, discount: 0, total: 10318, payment: 'paid', fulfillment: 'fulfilled', address: { name: 'Lucas Berg', line1: '22 Pine St', city: 'Denver', state: 'CO', zip: '80201', country: 'US' }, timeline: [{ time: 'Apr 4, 10:30 pm', event: 'Order placed', detail: '' }, { time: 'Apr 4, 10:31 pm', event: 'Payment captured', detail: '$103.18 via PayPal' }, { time: 'Apr 5, 9:00 am', event: 'Fulfilled', detail: 'Shipped via FedEx' }] },
  { id: '1038', num: 1038, date: 'Apr 4, 6:15 pm', customer: 'Nina Kowalski', email: 'nina.kowalski@gmail.com', items: [{ title: 'Hooded Sweatshirt', variant: 'XL / Grey', qty: 2, price: 6999 }, { title: 'Cargo Shorts', variant: 'L / Khaki', qty: 1, price: 3999 }], subtotal: 17997, shipping: 599, tax: 1440, discount: 0, total: 20036, payment: 'refunded', fulfillment: 'fulfilled', address: { name: 'Nina Kowalski', line1: '5 River Rd', city: 'Chicago', state: 'IL', zip: '60601', country: 'US' }, timeline: [{ time: 'Apr 4, 6:15 pm', event: 'Order placed', detail: '' }, { time: 'Apr 4, 6:16 pm', event: 'Payment captured', detail: '$200.36 via Stripe' }, { time: 'Apr 4, 7:00 pm', event: 'Fulfilled', detail: '' }, { time: 'Apr 5, 10:00 am', event: 'Refunded', detail: 'Full refund of $200.36 — customer requested' }] },
  { id: '1037', num: 1037, date: 'Apr 3, 4:20 pm', customer: 'Omar Hassan', email: 'omar.hassan@gmail.com', items: [{ title: 'Wool Beanie', variant: 'One Size / Red', qty: 3, price: 1999 }], subtotal: 5997, shipping: 599, tax: 480, discount: 600, total: 6476, payment: 'paid', fulfillment: 'partial', address: { name: 'Omar Hassan', line1: '101 Main St', city: 'San Francisco', state: 'CA', zip: '94102', country: 'US' }, timeline: [{ time: 'Apr 3, 4:20 pm', event: 'Order placed', detail: '' }, { time: 'Apr 3, 4:21 pm', event: 'Payment captured', detail: '$64.76 via Stripe' }, { time: 'Apr 4, 11:00 am', event: 'Partially fulfilled', detail: '2 of 3 items shipped' }] },
  { id: '1036', num: 1036, date: 'Apr 3, 11:30 am', customer: 'Elena Rossi', email: 'elena.rossi@live.com', items: [{ title: 'Silk Scarf', variant: 'Blue', qty: 1, price: 2999 }], subtotal: 2999, shipping: 599, tax: 240, discount: 0, total: 3838, payment: 'paid', fulfillment: 'fulfilled', address: { name: 'Elena Rossi', line1: '45 Via Roma', city: 'Miami', state: 'FL', zip: '33101', country: 'US' }, timeline: [{ time: 'Apr 3, 11:30 am', event: 'Order placed', detail: '' }, { time: 'Apr 3, 11:31 am', event: 'Payment captured', detail: '' }, { time: 'Apr 3, 5:00 pm', event: 'Fulfilled', detail: '' }] },
  { id: '1035', num: 1035, date: 'Apr 2, 3:00 pm', customer: 'David Kim', email: 'david.kim@proton.me', items: [{ title: 'Classic Cotton T-Shirt', variant: 'S / Black', qty: 1, price: 2499 }], subtotal: 2499, shipping: 599, tax: 200, discount: 250, total: 3048, payment: 'paid', fulfillment: 'unfulfilled', address: { name: 'David Kim', line1: '77 Sunset Blvd', city: 'Los Angeles', state: 'CA', zip: '90028', country: 'US' }, timeline: [{ time: 'Apr 2, 3:00 pm', event: 'Order placed', detail: '' }, { time: 'Apr 2, 3:01 pm', event: 'Payment captured', detail: '$30.48 via Stripe' }] },
];

export const PRODUCTS = [
  { id: 'p1', title: 'Classic Cotton T-Shirt', status: 'active', inventory: 142, type: 'T-Shirts', vendor: 'EcoCotton Co.', price: 2499, compareAt: 2999, cost: 800, sku: 'CCT-001', variants: [{ title: 'S / White', price: 2499, inventory: 25 }, { title: 'M / White', price: 2499, inventory: 3 }, { title: 'L / White', price: 2499, inventory: 30 }, { title: 'XL / White', price: 2499, inventory: 3 }, { title: 'S / Black', price: 2499, inventory: 20 }, { title: 'M / Black', price: 2499, inventory: 28 }, { title: 'L / Black', price: 2499, inventory: 18 }, { title: 'XL / Black', price: 2499, inventory: 15 }], description: 'A comfortable everyday cotton tee in multiple colors. Made from 100% organic cotton.' },
  { id: 'p2', title: 'Slim Fit Jeans', status: 'active', inventory: 67, type: 'Pants', vendor: 'DenimWorks', price: 5999, compareAt: 7499, cost: 2200, sku: 'SFJ-001', variants: [{ title: '30 / Indigo', price: 5999, inventory: 12 }, { title: '32 / Indigo', price: 5999, inventory: 1 }, { title: '34 / Indigo', price: 5999, inventory: 18 }, { title: '30 / Black', price: 5999, inventory: 14 }, { title: '32 / Black', price: 5999, inventory: 10 }, { title: '34 / Black', price: 5999, inventory: 12 }], description: 'Modern slim fit jeans with stretch comfort.' },
  { id: 'p3', title: 'Leather Belt', status: 'active', inventory: 34, type: 'Accessories', vendor: 'HideCraft', price: 3499, compareAt: null, cost: 1200, sku: 'LB-001', variants: [{ title: 'S / Brown', price: 3499, inventory: 12 }, { title: 'M / Brown', price: 3499, inventory: 5 }, { title: 'L / Brown', price: 3499, inventory: 17 }], description: 'Genuine leather belt with brushed metal buckle.' },
  { id: 'p4', title: 'Canvas Sneakers', status: 'active', inventory: 89, type: 'Footwear', vendor: 'StepUp', price: 4999, compareAt: 5999, cost: 1800, sku: 'CS-001', variants: [{ title: '8 / White', price: 4999, inventory: 10 }, { title: '9 / White', price: 4999, inventory: 15 }, { title: '10 / White', price: 4999, inventory: 2 }, { title: '11 / White', price: 4999, inventory: 12 }, { title: '8 / Black', price: 4999, inventory: 10 }, { title: '9 / Black', price: 4999, inventory: 12 }, { title: '10 / Black', price: 4999, inventory: 2 }, { title: '11 / Black', price: 4999, inventory: 8 }], description: 'Lightweight canvas sneakers for everyday wear.' },
  { id: 'p5', title: 'Wool Beanie', status: 'active', inventory: 210, type: 'Accessories', vendor: 'KnitCo', price: 1999, compareAt: null, cost: 600, sku: 'WB-001', variants: [{ title: 'One Size / Navy', price: 1999, inventory: 55 }, { title: 'One Size / Black', price: 1999, inventory: 50 }, { title: 'One Size / Red', price: 1999, inventory: 60 }, { title: 'One Size / Grey', price: 1999, inventory: 45 }], description: 'Soft merino wool beanie for cold days.' },
  { id: 'p6', title: 'Hooded Sweatshirt', status: 'active', inventory: 56, type: 'Outerwear', vendor: 'FleeceKing', price: 6999, compareAt: 7999, cost: 2500, sku: 'HS-001', variants: [{ title: 'M / Black', price: 6999, inventory: 12 }, { title: 'L / Black', price: 6999, inventory: 8 }, { title: 'XL / Black', price: 6999, inventory: 6 }, { title: 'M / Grey', price: 6999, inventory: 10 }, { title: 'L / Grey', price: 6999, inventory: 10 }, { title: 'XL / Grey', price: 6999, inventory: 10 }], description: 'Cozy fleece-lined hoodie with kangaroo pocket.' },
  { id: 'p7', title: 'Linen Shirt', status: 'draft', inventory: 0, type: 'Shirts', vendor: 'LinenLux', price: 4499, compareAt: null, cost: 1500, sku: 'LS-001', variants: [{ title: 'S / White', price: 4499, inventory: 0 }, { title: 'M / White', price: 4499, inventory: 0 }, { title: 'L / White', price: 4499, inventory: 0 }, { title: 'XL / White', price: 4499, inventory: 0 }], description: 'Lightweight linen shirt for warm weather.' },
  { id: 'p8', title: 'Cargo Shorts', status: 'active', inventory: 120, type: 'Pants', vendor: 'OutdoorGear', price: 3999, compareAt: 4999, cost: 1400, sku: 'CG-001', variants: [{ title: 'M / Khaki', price: 3999, inventory: 20 }, { title: 'L / Khaki', price: 3999, inventory: 25 }, { title: 'XL / Khaki', price: 3999, inventory: 15 }, { title: 'M / Olive', price: 3999, inventory: 20 }, { title: 'L / Olive', price: 3999, inventory: 25 }, { title: 'XL / Olive', price: 3999, inventory: 15 }], description: 'Durable cargo shorts with multiple pockets.' },
  { id: 'p9', title: 'Silk Scarf', status: 'archived', inventory: 8, type: 'Accessories', vendor: 'SilkHouse', price: 2999, compareAt: null, cost: 1000, sku: 'SS-001', variants: [{ title: 'Blue', price: 2999, inventory: 4 }, { title: 'Red', price: 2999, inventory: 4 }], description: 'Elegant silk scarf with hand-rolled edges.' },
  { id: 'p10', title: 'Running Shoes', status: 'active', inventory: 75, type: 'Footwear', vendor: 'SprintTech', price: 8999, compareAt: 10999, cost: 3200, sku: 'RS-001', variants: [{ title: '8 / Black', price: 8999, inventory: 8 }, { title: '9 / Black', price: 8999, inventory: 10 }, { title: '10 / Black', price: 8999, inventory: 12 }, { title: '11 / Black', price: 8999, inventory: 8 }, { title: '8 / White', price: 8999, inventory: 8 }, { title: '9 / White', price: 8999, inventory: 10 }, { title: '10 / White', price: 8999, inventory: 10 }, { title: '11 / White', price: 8999, inventory: 9 }], description: 'Lightweight performance running shoes with responsive cushioning.' },
];

export const CUSTOMERS = [
  { id: 'c1', name: 'Sarah Chen', email: 'sarah.chen@gmail.com', orders: 12, spent: 289400, location: 'Portland, OR', joined: 'Jan 15, 2026', phone: '+1 503-555-0142', addresses: [{ line1: '742 Evergreen Terrace', city: 'Portland', state: 'OR', zip: '97201', country: 'US', default: true }], notes: 'VIP customer — always purchases during sales events.' },
  { id: 'c2', name: 'James Wilson', email: 'james.wilson@outlook.com', orders: 8, spent: 156200, location: 'Austin, TX', joined: 'Feb 3, 2026', phone: '+1 512-555-0198', addresses: [{ line1: '15 Oak Lane', city: 'Austin', state: 'TX', zip: '73301', country: 'US', default: true }], notes: '' },
  { id: 'c3', name: 'Amira Patel', email: 'amira.patel@yahoo.com', orders: 5, spent: 87500, location: 'Brooklyn, NY', joined: 'Feb 18, 2026', phone: '+1 718-555-0167', addresses: [{ line1: '88 Maple Ave', city: 'Brooklyn', state: 'NY', zip: '11201', country: 'US', default: true }], notes: '' },
  { id: 'c4', name: 'Lucas Berg', email: 'lucas.berg@proton.me', orders: 3, spent: 45970, location: 'Denver, CO', joined: 'Mar 1, 2026', phone: '', addresses: [{ line1: '22 Pine St', city: 'Denver', state: 'CO', zip: '80201', country: 'US', default: true }], notes: '' },
  { id: 'c5', name: 'Nina Kowalski', email: 'nina.kowalski@gmail.com', orders: 15, spent: 412300, location: 'Chicago, IL', joined: 'Dec 20, 2025', phone: '+1 312-555-0134', addresses: [{ line1: '5 River Rd', city: 'Chicago', state: 'IL', zip: '60601', country: 'US', default: true }], notes: 'Top customer by lifetime value. Prefers expedited shipping.' },
  { id: 'c6', name: 'Omar Hassan', email: 'omar.hassan@gmail.com', orders: 7, spent: 98700, location: 'San Francisco, CA', joined: 'Jan 28, 2026', phone: '+1 415-555-0189', addresses: [{ line1: '101 Main St', city: 'San Francisco', state: 'CA', zip: '94102', country: 'US', default: true }], notes: '' },
  { id: 'c7', name: 'Elena Rossi', email: 'elena.rossi@live.com', orders: 4, spent: 67890, location: 'Miami, FL', joined: 'Mar 12, 2026', phone: '', addresses: [{ line1: '45 Via Roma', city: 'Miami', state: 'FL', zip: '33101', country: 'US', default: true }], notes: '' },
  { id: 'c8', name: 'David Kim', email: 'david.kim@proton.me', orders: 2, spent: 10998, location: 'Los Angeles, CA', joined: 'Mar 25, 2026', phone: '+1 213-555-0156', addresses: [{ line1: '77 Sunset Blvd', city: 'Los Angeles', state: 'CA', zip: '90028', country: 'US', default: true }], notes: '' },
];

export const DISCOUNTS = [
  { id: 'd1', code: 'SPRING25', type: 'percentage', value: 25, used: 142, limit: 500, active: true, start: 'Mar 1, 2026', end: 'Apr 30, 2026', minAmount: 5000 },
  { id: 'd2', code: 'WELCOME10', type: 'percentage', value: 10, used: 89, limit: null as number | null, active: true, start: 'Jan 1, 2026', end: null as string | null, minAmount: null as number | null },
  { id: 'd3', code: 'FREESHIP', type: 'free_shipping', value: 0, used: 234, limit: null as number | null, active: true, start: 'Feb 1, 2026', end: null as string | null, minAmount: 3000 },
  { id: 'd4', code: 'SAVE15', type: 'fixed_amount', value: 1500, used: 50, limit: 50, active: false, start: 'Jan 15, 2026', end: 'Feb 28, 2026', minAmount: null as number | null },
  { id: 'd5', code: 'VIP30', type: 'percentage', value: 30, used: 12, limit: 20, active: true, start: 'Apr 1, 2026', end: 'Apr 15, 2026', minAmount: 10000 },
];
